# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do  
  lane :internal_appbundle do
    upload_to_play_store(      
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
    )
  end

  lane :production_appbundle do
    upload_to_play_store(      
      track: 'production',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
    )
  end


  lane :gp_promote_internal_production do
    upload_to_play_store(      
      track: 'internal',
      skip_upload_aab: true,
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      track_promote_to: 'production',
    )
  end
  


